name: "Sparse Checkout"
description: ""

inputs:
  patterns:
    description: The pattern for the sparse checkout.
    default: "*"
    required: true
  branch:
    description: The branch to checkout.
    required: false

runs:
  using: "composite"
  steps:
    - name: "Sparse Checkout"
      shell: bash
      run: |
        REPO="https://${GITHUB_ACTOR}:${{ github.token }}@github.com/${GITHUB_REPOSITORY}.git"
        BRANCH="${{ inputs.branch }}"
        DEFAULT_BRANCH="${GITHUB_REF/#refs\/heads\//}"
        REF="${BRANCH:-$DEFAULT_BRANCH}"
        git clone --filter=blob:none --no-checkout --depth 1 --sparse $REPO .
        git sparse-checkout init --cone --sparse-index
        git sparse-checkout set ${{ inputs.patterns }}
        git fetch --progress --no-tags --prune --depth=1 origin $REF:$REF
        git checkout --progress $REF
